blog/config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
  root "welcome#index"
  resources :posts do
  	resources :comments
  end

  # get 'posts/new'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

blog/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

blog/app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  # validates :email, presence: true
  validates :comment, presence: true
  validates_format_of :email, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i
end

blog/app/models/post.rb
class Post < ApplicationRecord
  has_many :comments
  accepts_nested_attributes_for :comments
  validates :title, presence: true,
                    length: { in: 15..75 } 
  validates_uniqueness_of :title, :case_sensitive => false
  validates :author, presence: true,
                    length: { minimum: 5 }
  validates_format_of :author, :with => /[a-z]/   
  validates :text, presence: true,
                    length: { in: 0..2000 }         

end


	

blog/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

blog/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
        @post = Post.find(params[:post_id])
        @comment = @posts.comments.build 
    end

    def index
        @post = Post.find(params[:post_id])
        @comments = @post.comments.all
    end

    def create
        @post = Post.find(params[:post_id])
        @comment = @post.comments.new(comment_params)
        if @comment.save
            redirect_to post_path(@post)
        else
            flash[:notice] = "* Unable to create the comment !"
            redirect_to post_path(@post)
          
        end
    end

        def destroy
        	@post = Post.find(params[:post_id])
          @comment = @post.comments.find(params[:id])
          
          @comment.destroy
          flash[:notice] = "Destroyed homie ! "
          redirect_to post_path(@post)
        end


    # def show
    #     @post = Post.find(params)

      private
        def comment_params
          params.require(:comment).permit(:comment, :name, :email)
        end
    end

blog/app/controllers/posts_controller.rb
class PostsController < ApplicationController
	
  def index
   @posts = Post.all.order(date: :desc)
  end 

  def new
    @post = Post.new  
	end

  def edit
    @post = Post.find(params[:id])
  end

  def update
  @post = Post.find(params[:id])
 
  if @post.update(post_params)
    redirect_to @post
  else
    render 'edit'
  end
  end


  def show
    @post = Post.find(params[:id])
    @comment = @post.comments.build
  end

  def create
  @post = Post.new(post_params)
  if @post.save
    redirect_to @post
  else
    render 'new'
  end
end

  def post_params
    params.require(:post).permit(:title, :date, :text, :author)
  end

  def destroy
  @post = Post.find(params[:id])
  @post.destroy
  redirect_to posts_path
  end
end

blog/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

blog/app/helpers/application_helper.rb
module ApplicationHelper
end

blog/app/helpers/comments_helper.rb
module CommentsHelper
end

blog/app/helpers/posts_helper.rb
module PostsHelper
end

blog/app/helpers/welcome_helper.rb
module WelcomeHelper
end

blog/app/views/comments/_comment.html.erb
<% if comment.persisted? %>
	<p>
	  <strong>Name:</strong>
	  <%= comment.name %>
	</p>
	 
	<p>
	  <strong>Comments:</strong>
	  <%= comment.comment %>
	</p>

	<p>
	  <strong>Email:</strong>
	  <%= comment.email %>
	</p>
	<p>
	  <%= link_to 'Delete', post_comment_path(@post, comment), :class=>'btn btn-danger',
	               method: :delete,
	               data: { confirm: 'You fo realzzzz, dawg???' } %>
	</p>
	</br>
<%end%>

blog/app/views/comments/_form.html.erb
<%= form_for [ @post, @post.comments.build ], validate:  true  do |f| %>
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :comment %><br>
    <%= f.text_area :comment %>
  </p>
  <p>
    <%= f.label :email %><br>
    <%= f.email_field :email %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %> 

blog/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
<%= javascript_include_tag :defaults, "rails.validations" %>
<nav class="navbar navbar-inverse navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/welcome/index">Shalom</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><a href="/posts">My Blog <span class="sr-only">(current)</span></a></li>
      
          </ul>
        </li>
      </ul>
      
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

    <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
  <!-- Indicators -->
  <ol class="carousel-indicators">
    <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
    <li data-target="#carousel-example-generic" data-slide-to="1"></li>
    <li data-target="#carousel-example-generic" data-slide-to="2"></li>
  </ol>

  <!-- Wrapper for slides -->
  <div class="carousel-inner" role="listbox">
    <div class="item active">
      <%= image_tag("peanuts_pic") %>
      <div class="carousel-caption">
        ...
      </div>
    </div>
    <div class="item">
      <%= image_tag("stone_cold") %>
      <div class="carousel-caption">
        ...
      </div>
    </div>
    <div class="item">
      <%= image_tag("logo") %>
      <div class="carousel-caption">
        ...
      </div>
    ...
  </div>

  <!-- Controls -->
  <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
    <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>
  </head>

  <body class="container">
    <% if flash %>
      <div class = "alert alert-danger" >
        <%= flash[:notice]%>
      </div>
    <%end%>
    <%= yield %>
  </body>
</html>

blog/app/views/posts/_form.html.erb
<%= form_for @post,:validate => true do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(post.errors.count, "error") %> prohibited
        this post from being saved:
      </h2>
      <ul>
        <% @post.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
    <div class="form-group">
      <%= f.label :title, :class=> "control-label" %>
      <%= f.text_field :title, :class=> 'form-control' %>
    </div>
  

    <p>
    <%= f.label :date %><br>
    <%= f.date_field :date, :class=> 'form-control' %>
  </p>
 
  <p>
    <%= f.label :text %><br>
    <%= f.text_area :text, :class=> 'form-control', :rows => 5 %>
  </p>

   <p>
    <%= f.label :author %><br>
    <%= f.text_field :author, :class=> 'form-control' %>
  </p>
 
 
  <p>
    <%= f.submit "Update", :class=>'btn btn-default' %>
  </p>


<% end %>

blog/app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render 'form', post: @post %>
 
<%= form_for :post, url: post_path(@post), method: :patch do |f| %>
 
<!--   <% if @post.errors.any? %> -->
    <!-- <div id="error_explanation">
      <h2>
        <%= pluralize(@post.errors.count, "error") %> prohibited
        this post from being saved:
      </h2>
      <ul>
        <% @post.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div> -->
<!--   <% end %>
  -->
  <!-- <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
 

    <p>
    <%= f.label :date %><br>
    <%= f.date_field :date %>
  </p> -->
 
  <!-- <p>
    <%= f.label :text %><br>
    <%= f.text_area :text %>
  </p>
 
 
  <p>
    <%= f.submit %>
  </p>
 
<% end %> -->
 
<%= link_to 'Back', posts_path, :class=> 'btn btn-success' %>

blog/app/views/posts/index.html.erb
<h1>My Life is Worth Peanuts</h1>
 <%= link_to 'New Post', new_post_path %>


<% @posts.each do |post| %>
  <section>
    <header>
      <h1><%= post.title %></h1>
    </header>
    <article>
      <p> <%= post.text %> </p>
      <p> by <%= post.author %> </p>
    </article>
    <footer>
      <%= link_to 'Show', post_path(post), :class=> 'btn btn-success' %>
      <%= link_to 'Edit', edit_post_path(post), :class=> 'btn btn-primary' %>
      <%= link_to 'delete', post_path(post), :class=>'btn btn-danger',
                method: :delete,
                data: { confirm: 'Are you sure?' } %>

    </footer>
  </section>

<% end %>
<!-- 
<table>
  <tr>
    <th>Title</th>
    <th>Date</th>
    <th>Text</th>

  </tr>
 
  <% @posts.each do |post| %>
    <tr>
      <td><%= post.title %></td>
      <td><%= post.date %></td>
      <td><%= post.text %></td>
      <td><%= link_to 'Show', post_path(post) %></td>
      <td><%= link_to 'Edit', edit_post_path(post) %></td>
      <td><%= link_to 'Destroy', post_path(post),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table> -->

blog/app/views/posts/new.html.erb
<h1> New Post </h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path, :class=> 'btn btn-success'

blog/app/views/posts/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>
 <p>
   <strong>Date:</strong>
  <%= @post.date %>
</p>

<p>
  
  <%= @post.text %>
</p>
<p>
by <%= @post.author %>
</p>

<h2>Comments</h2>
<%= render @post.comments %>

<h2>Add a comment:</h2>
<%= render 'comments/form' %>


<%= link_to 'Edit', edit_post_path( @post ) %>
<%= link_to 'Back', posts_path, :class=> 'btn btn-success' %>

blog/app/views/posts/view.html.erb
<h1>My Life</h1>
 
<table>
  <tr>
    <th>Title</th>
    <th>Date</th>
    <th>Text</th>

  </tr>
 
  <% @posts.each do |post| %>
    <tr>
      <td><%= post.title %></td>
      <td><%= post.date %></td>
      <td><%= post.text %></td>
      <td><%= link_to 'Show', post_path(post) %></td>
    </tr>
  <% end %>
</table>

blog/app/views/welcome/index.html.erb
<h1>Welcome to my World</h1>

<p>The Immaculate Conception of Stan Shalom Chin</p>

<%= link_to 'My Blog', controller: 'posts' %>